import 'dart:async';

import 'package:dartz/dartz.dart';

import 'exceptions.dart';
import 'failures.dart';

mixin HandlingExceptionManager {
  Future<Either<Failure, T>> wrapHandling<T>({
    required Future<Right<Failure, T>> Function() tryCall,
  }) async {
    try {
      final right = await tryCall();
      return right;
    } on ServerException catch (e) {
      return Left(ServerFailure(message: e.message));
    } catch (e) {
      return Left(ServerFailure(message: ".message"));
    }
  }
}
